name: Pull Request Validation
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
        working-directory: ./scripts
      - name: Run Validation
        run: npm run validate
        working-directory: ./scripts